apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:       
      - name: back-ventas
        image: felipesalazar24/back-ventas:latest
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql-service:3306/tienda_db"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "root123"
        ports:
          - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: back-ventas-service
  namespace: tienda
spec:
  selector:
    app: back-ventas
  ports:   
    - protocol: TCP
      port: 8082
      targetPort: 8082